#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ROOT="${REMOTE_MCP_ROOT:-$SCRIPT_ROOT}"
CONTROL="$ROOT/apps/control-plane"
ENV_FILE="$CONTROL/.env.local"
RUNTIME_ENV="${REMOTE_MCP_RUNTIME_ENV:-$ROOT/.data/launchd-runtime.env}"
TAILSCALE_BIN="${TAILSCALE_BIN:-}"
TASK_FREEZE_FILE="${REMOTE_MCP_TASK_ADMISSION_FREEZE_FILE:-$ROOT/.data/task-admission.frozen}"
EFFECT_FREEZE_FILE="${REMOTE_MCP_EFFECT_ADMISSION_FREEZE_FILE:-$ROOT/.data/effect-admission.frozen}"
INGRESS_FREEZE_FILE="${REMOTE_MCP_PUBLIC_INGRESS_FREEZE_FILE:-$ROOT/.data/public-ingress.frozen}"

JAZZ_PID=""
WEB_PID=""

log() {
  printf '[remote-mcp-stack] %s %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*"
}

cleanup() {
  set +e
  if [[ -n "$WEB_PID" ]] && kill -0 "$WEB_PID" 2>/dev/null; then
    kill "$WEB_PID" 2>/dev/null
    wait "$WEB_PID" 2>/dev/null
  fi
  if [[ -n "$JAZZ_PID" ]] && kill -0 "$JAZZ_PID" 2>/dev/null; then
    kill "$JAZZ_PID" 2>/dev/null
    wait "$JAZZ_PID" 2>/dev/null
  fi
}

shutdown() {
  log "shutdown requested"
  trap - EXIT INT TERM HUP
  cleanup
  exit 0
}

trap cleanup EXIT
trap shutdown INT TERM HUP

for required in "$ENV_FILE" "$RUNTIME_ENV" "$CONTROL/.next/BUILD_ID"; do
  if [[ ! -e "$required" ]]; then
    log "required path is missing: $required"
    exit 1
  fi
done

# Generated by install-launch-agent.sh from the pinned Nix dev shell.
# shellcheck disable=SC1090
source "$RUNTIME_ENV"
: "${NODE_BIN:?NODE_BIN missing from runtime env}"
: "${PNPM_BIN:?PNPM_BIN missing from runtime env}"
: "${TAILSCALE_BIN:?TAILSCALE_BIN missing from runtime env}"
[[ -x "$NODE_BIN" ]] || { log "NODE_BIN is not executable: $NODE_BIN"; exit 1; }
[[ -x "$PNPM_BIN" ]] || { log "PNPM_BIN is not executable: $PNPM_BIN"; exit 1; }
[[ -x "$TAILSCALE_BIN" ]] || { log "TAILSCALE_BIN is not executable: $TAILSCALE_BIN"; exit 1; }

export PATH="$(dirname "$NODE_BIN"):$(dirname "$PNPM_BIN"):$(dirname "$TAILSCALE_BIN"):/run/current-system/sw/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export HOME="${HOME:-/Users/test}"
export TERM_PROGRAM="${TERM_PROGRAM:-remote-mcp-launchd}"
export REMOTE_MCP_ROOT="$ROOT"
export REMOTE_MCP_TASK_ADMISSION_FREEZE_FILE="$TASK_FREEZE_FILE"
export REMOTE_MCP_EFFECT_ADMISSION_FREEZE_FILE="$EFFECT_FREEZE_FILE"
export REMOTE_MCP_PUBLIC_INGRESS_FREEZE_FILE="$INGRESS_FREEZE_FILE"
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a
export NODE_ENV=production
export JAZZ_BACKEND_DATA_PATH="${JAZZ_BACKEND_DATA_PATH:-$ROOT/.data/jazz-backend-runtime.db}"
mkdir -p "$(dirname "$JAZZ_BACKEND_DATA_PATH")"

JAZZ_PORT="${JAZZ_PORT:-1625}"
WEB_PORT="${WEB_PORT:-3000}"

wait_for_port() {
  local name="$1" host="$2" port="$3" pid="$4" timeout="$5"
  local deadline=$((SECONDS + timeout))
  until /usr/bin/nc -z "$host" "$port" >/dev/null 2>&1; do
    if ! kill -0 "$pid" 2>/dev/null; then
      log "$name exited before becoming ready"
      wait "$pid" || true
      return 1
    fi
    if (( SECONDS >= deadline )); then
      log "timed out waiting for $name on $host:$port"
      return 1
    fi
    sleep 0.5
  done
  log "$name is ready on $host:$port"
}

# If a clean-reseed handoff is pending, durably record that this recovered
# authority is about to be started before any supervised runtime subprocess is
# invoked. Recovery must never infer "never started" from process absence alone.
"$ROOT/ops/macos/mark-jazz-clean-reseed-startup-attempted.sh"

log "runtime node=$($NODE_BIN --version) pnpm=$($PNPM_BIN --version)"
log "Jazz backend runtime path=$JAZZ_BACKEND_DATA_PATH"
log "starting Jazz authority"
(
  cd "$CONTROL"
  exec "$PNPM_BIN" jazz:serve
) &
JAZZ_PID=$!
wait_for_port "Jazz authority" 127.0.0.1 "$JAZZ_PORT" "$JAZZ_PID" 45
log "starting production Next control plane"
(
  cd "$CONTROL"
  exec "$PNPM_BIN" start
) &
WEB_PID=$!
wait_for_port "control plane" 127.0.0.1 "$WEB_PORT" "$WEB_PID" 45

if [[ -e "$INGRESS_FREEZE_FILE" ]]; then
  log "public ingress maintenance is active"
  "$ROOT/ops/macos/cutover-control.sh" ingress-enforce-frozen
else
  log "reasserting Tailscale Funnel -> http://127.0.0.1:$WEB_PORT"
  "$TAILSCALE_BIN" funnel --bg --yes "$WEB_PORT"
  "$TAILSCALE_BIN" funnel status
fi

log "stack is healthy; monitoring child processes"
while :; do
  if ! kill -0 "$JAZZ_PID" 2>/dev/null; then
    log "Jazz authority exited"
    wait "$JAZZ_PID" || true
    exit 1
  fi
  if ! kill -0 "$WEB_PID" 2>/dev/null; then
    log "control plane exited"
    wait "$WEB_PID" || true
    exit 1
  fi
  sleep 5
done
